// ─── Users / Students ───────────────────────────────────────────────
export const MOCK_USER = {
  firstName: "Priya",
  lastName: "Sharma",
  username: "priya-sharma",
  bio: "Estudiante de Ingeniería Informática en la UPM, de India. Buscando prácticas en desarrollo web.",
  region: "Asia",
  university: "Universidad Politécnica de Madrid",
  photo: null,
  memberSince: "Mar 2026",
  interests: [
    "Prácticas en empresa",
    "CV formato europeo",
    "Networking profesional",
    "Regulaciones migratorias",
    "Preparación de entrevistas",
    "Sector tecnología",
  ],
  completionPercent: 30,
};

export const MOCK_STUDENTS = [
  {
    name: "Carlos Mendoza",
    region: "LATAM",
    country: "Colombia",
    university: "Universidad Complutense de Madrid",
    field: "Administración de Empresas",
    avatar: "CM",
    color: "bg-blue-400",
    interests: ["Networking profesional", "Emprendimiento", "Sector finanzas"],
  },
  {
    name: "Amina Diallo",
    region: "África",
    country: "Senegal",
    university: "Universidad de Barcelona",
    field: "Ciencias Políticas",
    avatar: "AD",
    color: "bg-pink-400",
    interests: ["Regulaciones migratorias", "Habilidades interculturales"],
  },
  {
    name: "Wei Zhang",
    region: "Asia",
    country: "China",
    university: "IE University",
    field: "Data Science",
    avatar: "WZ",
    color: "bg-yellow-400",
    interests: ["Sector tecnología", "CV y LinkedIn", "Empleo a tiempo completo"],
  },
  {
    name: "Fatima Al-Hassan",
    region: "Oriente Medio",
    country: "Jordania",
    university: "Universidad Autónoma de Madrid",
    field: "Ingeniería Biomédica",
    avatar: "FA",
    color: "bg-purple-400",
    interests: ["Sector salud", "Investigación académica", "Prácticas en empresa"],
  },
  {
    name: "Lucas Ferreira",
    region: "LATAM",
    country: "Brasil",
    university: "Universidad de Salamanca",
    field: "Marketing Digital",
    avatar: "LF",
    color: "bg-green-400",
    interests: ["Marca personal", "Emprendimiento", "Networking profesional"],
  },
  {
    name: "Nguyen Thi Mai",
    region: "Asia",
    country: "Vietnam",
    university: "Universidad de Valencia",
    field: "Arquitectura",
    avatar: "NM",
    color: "bg-orange-400",
    interests: ["Sector ingeniería", "Portfolio profesional", "Prácticas en empresa"],
  },
];

// ─── Mentors ────────────────────────────────────────────────────────
export const MOCK_MENTORS = [
  {
    id: "elena-garcia",
    name: "Elena García Ruiz",
    role: "Directora de RRHH",
    company: "Accenture España",
    avatar: "EG",
    color: "bg-indigo-400",
    specialties: ["Selección de talento", "Employer branding", "Diversidad e inclusión"],
    bio: "15 años en recursos humanos. Especialista en integración de talento internacional en grandes consultoras.",
    sessionsCompleted: 24,
    rating: 4.9,
  },
  {
    id: "miguel-torres",
    name: "Miguel Ángel Torres",
    role: "Engineering Manager",
    company: "Cabify",
    avatar: "MT",
    color: "bg-teal-400",
    specialties: ["Desarrollo de software", "Startups", "Tech careers"],
    bio: "Ex-Google, ahora liderando equipos de ingeniería en Cabify. Mentor de talento tech internacional.",
    sessionsCompleted: 18,
    rating: 4.8,
  },
  {
    id: "isabel-fernandez",
    name: "Isabel Fernández",
    role: "Abogada de Extranjería",
    company: "Deloitte Legal",
    avatar: "IF",
    color: "bg-rose-400",
    specialties: ["Permisos de trabajo", "Visados", "Regulación migratoria"],
    bio: "Especialista en derecho migratorio y permisos laborales para profesionales no-UE en España.",
    sessionsCompleted: 32,
    rating: 5.0,
  },
  {
    id: "andres-moreno",
    name: "Andrés Moreno",
    role: "Director Comercial",
    company: "Banco Santander",
    avatar: "AM",
    color: "bg-amber-400",
    specialties: ["Banca", "Finanzas internacionales", "Networking"],
    bio: "20 años en banca internacional. Apasionado por abrir puertas a nuevos profesionales.",
    sessionsCompleted: 15,
    rating: 4.7,
  },
];

// ─── Workshops ──────────────────────────────────────────────────────
export const MOCK_WORKSHOPS = [
  {
    id: "cv-europeo",
    title: "CV europeo: formato y estrategia",
    date: "22 Mar 2026",
    time: "10:00 - 12:00",
    format: "Online",
    mentor: "Elena García Ruiz",
    spots: 8,
    maxSpots: 20,
    tags: ["CV", "Empleabilidad"],
    description: "Aprende a crear un CV que cumpla con los estándares europeos y destaque tu perfil internacional.",
  },
  {
    id: "regulaciones-migratorias",
    title: "Regulaciones migratorias para estudiantes",
    date: "29 Mar 2026",
    time: "16:00 - 18:00",
    format: "Presencial - Madrid",
    mentor: "Isabel Fernández",
    spots: 15,
    maxSpots: 25,
    tags: ["Legal", "Migraciones"],
    description: "Todo sobre permisos de trabajo, prórroga de estancia y vías legales para quedarte en España.",
  },
  {
    id: "networking-linkedin",
    title: "Networking estratégico en LinkedIn",
    date: "5 Abr 2026",
    time: "11:00 - 13:00",
    format: "Online",
    mentor: "Miguel Ángel Torres",
    spots: 3,
    maxSpots: 15,
    tags: ["LinkedIn", "Networking"],
    description: "Cómo construir una red de contactos profesional desde cero en un país nuevo.",
  },
  {
    id: "entrevistas-tecnicas",
    title: "Preparación de entrevistas técnicas",
    date: "12 Abr 2026",
    time: "10:00 - 12:30",
    format: "Online",
    mentor: "Miguel Ángel Torres",
    spots: 12,
    maxSpots: 20,
    tags: ["Entrevistas", "Tech"],
    description: "Simulacros de entrevistas técnicas y tips para superar procesos de selección en tech.",
  },
  {
    id: "elevator-pitch",
    title: "Elevator pitch y marca personal",
    date: "19 Abr 2026",
    time: "16:00 - 17:30",
    format: "Presencial - Barcelona",
    mentor: "Elena García Ruiz",
    spots: 10,
    maxSpots: 20,
    tags: ["Comunicación", "Marca personal"],
    description: "Aprende a presentarte en 60 segundos y diferenciarte del resto de candidatos.",
  },
];

// ─── Companies ──────────────────────────────────────────────────────
export const MOCK_COMPANIES = [
  {
    slug: "accenture-espana",
    name: "Accenture España",
    sector: "Consultoría & Tecnología",
    location: "Madrid",
    openRoles: 3,
    hiresNonEU: true,
    logo: "AC",
    color: "bg-purple-100 text-purple-700",
    description: "Líder global en servicios profesionales con fuerte compromiso en diversidad.",
  },
  {
    slug: "cabify",
    name: "Cabify",
    sector: "Tecnología & Movilidad",
    location: "Madrid (Remoto)",
    openRoles: 2,
    hiresNonEU: true,
    logo: "CB",
    color: "bg-violet-100 text-violet-700",
    description: "Startup de movilidad urbana con equipos internacionales y cultura remote-first.",
  },
  {
    slug: "banco-santander",
    name: "Banco Santander",
    sector: "Banca & Finanzas",
    location: "Madrid, Barcelona",
    openRoles: 4,
    hiresNonEU: true,
    logo: "BS",
    color: "bg-red-100 text-red-700",
    description: "Uno de los mayores bancos del mundo, con programas de prácticas para talento internacional.",
  },
  {
    slug: "inditex",
    name: "Inditex",
    sector: "Retail & Moda",
    location: "A Coruña, Madrid",
    openRoles: 5,
    hiresNonEU: true,
    logo: "IN",
    color: "bg-blue-100 text-blue-700",
    description: "Grupo líder en distribución de moda con presencia global y equipos multiculturales.",
  },
  {
    slug: "repsol",
    name: "Repsol",
    sector: "Energía",
    location: "Madrid",
    openRoles: 2,
    hiresNonEU: true,
    logo: "RP",
    color: "bg-orange-100 text-orange-700",
    description: "Compañía energética global con programas de becas y prácticas para ingenieros.",
  },
  {
    slug: "glovo",
    name: "Glovo",
    sector: "Tecnología & Delivery",
    location: "Barcelona (Remoto)",
    openRoles: 3,
    hiresNonEU: true,
    logo: "GL",
    color: "bg-green-100 text-green-700",
    description: "App de delivery con cultura startup, equipos diversos y crecimiento rápido.",
  },
  {
    slug: "telefonica",
    name: "Telefónica",
    sector: "Telecomunicaciones",
    location: "Madrid",
    openRoles: 6,
    hiresNonEU: true,
    logo: "TF",
    color: "bg-cyan-100 text-cyan-700",
    description: "Multinacional de telecomunicaciones con programa Talentum para jóvenes profesionales.",
  },
  {
    slug: "bbva",
    name: "BBVA",
    sector: "Banca & Tecnología",
    location: "Madrid, Bilbao",
    openRoles: 3,
    hiresNonEU: true,
    logo: "BB",
    color: "bg-indigo-100 text-indigo-700",
    description: "Banco digital líder con fuerte inversión en tecnología e innovación.",
  },
];

// ─── Job Opportunities ──────────────────────────────────────────────
export const MOCK_JOBS = [
  {
    id: "becario-marketing",
    role: "Becario/a Marketing Digital",
    company: "Accenture España",
    location: "Madrid",
    type: "Prácticas",
    salary: "800€/mes",
    posted: "Hace 2 días",
    deadline: "15 Abr 2026",
    description: "Apoyo en campañas de marketing digital para clientes internacionales.",
  },
  {
    id: "asistente-investigacion",
    role: "Asistente de Investigación",
    company: "Universidad de Barcelona",
    location: "Barcelona",
    type: "Media jornada",
    salary: "1.000€/mes",
    posted: "Hace 5 días",
    deadline: "30 Mar 2026",
    description: "Investigación en ciencias sociales con enfoque en migración y integración.",
  },
  {
    id: "dev-junior-frontend",
    role: "Desarrollador/a Junior Frontend",
    company: "Cabify",
    location: "Remoto España",
    type: "Tiempo completo",
    salary: "28.000€/año",
    posted: "Hace 1 día",
    deadline: "20 Abr 2026",
    description: "Desarrollo de interfaces con React y TypeScript en el equipo de rider experience.",
  },
  {
    id: "ingeniero-procesos",
    role: "Ingeniero/a de Procesos",
    company: "Repsol",
    location: "Madrid",
    type: "Prácticas",
    salary: "900€/mes",
    posted: "Hace 3 días",
    deadline: "10 Abr 2026",
    description: "Prácticas en optimización de procesos industriales en la división de refino.",
  },
  {
    id: "analista-datos",
    role: "Analista de Datos Junior",
    company: "BBVA",
    location: "Madrid",
    type: "Tiempo completo",
    salary: "26.000€/año",
    posted: "Hace 4 días",
    deadline: "25 Abr 2026",
    description: "Análisis de datos financieros y creación de dashboards para el equipo de riesgos.",
  },
  {
    id: "community-manager",
    role: "Community Manager",
    company: "Glovo",
    location: "Barcelona",
    type: "Tiempo completo",
    salary: "24.000€/año",
    posted: "Hace 1 semana",
    deadline: "5 Abr 2026",
    description: "Gestión de redes sociales y comunicación de marca para mercados LATAM.",
  },
];

// ─── Messages / Inbox ───────────────────────────────────────────────
export const MOCK_MESSAGES = [
  {
    from: "Elena García Ruiz",
    avatar: "EG",
    color: "bg-indigo-400",
    subject: "Próxima sesión de mentoría",
    preview: "Hola Priya, quería confirmar nuestra sesión del jueves a las 16:00. ¿Tienes tu CV actualizado?",
    time: "Hace 2h",
    unread: true,
  },
  {
    from: "Equipo Puente",
    avatar: "P",
    color: "bg-[var(--primary)]",
    subject: "Bienvenida al programa",
    preview: "¡Bienvenida a Puente! Tu perfil ha sido creado. Completa tu perfil al 70% para acceder a...",
    time: "Hace 1 día",
    unread: true,
  },
  {
    from: "Carlos Mendoza",
    avatar: "CM",
    color: "bg-blue-400",
    subject: "Grupo de estudio",
    preview: "¡Hola! Estamos formando un grupo de estudio para preparar entrevistas. ¿Te apuntas?",
    time: "Hace 2 días",
    unread: false,
  },
  {
    from: "Isabel Fernández",
    avatar: "IF",
    color: "bg-rose-400",
    subject: "Documentos para el NIE",
    preview: "Te adjunto la lista de documentos necesarios para la renovación del NIE que mencionaste...",
    time: "Hace 3 días",
    unread: false,
  },
];

// ─── Activity Feed (Scroll) ────────────────────────────────────────
export const MOCK_ACTIVITY = [
  {
    user: "Carlos Mendoza",
    avatar: "CM",
    color: "bg-blue-400",
    action: "compartió un recurso",
    content: "Guía completa para búsqueda de empleo en España para extranjeros. Muy útil para los que acaban de llegar.",
    time: "Hace 1h",
    likes: 12,
    comments: 3,
  },
  {
    user: "Elena García Ruiz",
    avatar: "EG",
    color: "bg-indigo-400",
    action: "publicó un consejo",
    content: "Tip: Al adaptar vuestro CV al formato europeo, incluir siempre vuestra foto profesional. En España es costumbre y los reclutadores lo esperan.",
    time: "Hace 3h",
    likes: 28,
    comments: 7,
  },
  {
    user: "Amina Diallo",
    avatar: "AD",
    color: "bg-pink-400",
    action: "celebró un logro",
    content: "¡Acabo de conseguir una entrevista en Deloitte para prácticas de verano! Gracias al taller de CV de la semana pasada. 🎉",
    time: "Hace 5h",
    likes: 34,
    comments: 11,
  },
  {
    user: "Miguel Ángel Torres",
    avatar: "MT",
    color: "bg-teal-400",
    action: "compartió una oportunidad",
    content: "Cabify busca desarrolladores junior. No requieren experiencia previa, solo ganas de aprender. Ideal para estudiantes del programa.",
    time: "Hace 8h",
    likes: 45,
    comments: 15,
  },
  {
    user: "Wei Zhang",
    avatar: "WZ",
    color: "bg-yellow-400",
    action: "hizo una pregunta",
    content: "¿Alguien sabe cuánto tarda la respuesta de la oficina de extranjería para la modificación del permiso de estudios a trabajo?",
    time: "Hace 1 día",
    likes: 8,
    comments: 6,
  },
  {
    user: "Equipo Puente",
    avatar: "P",
    color: "bg-[var(--primary)]",
    action: "anunció un evento",
    content: "Nuevo taller confirmado: 'Networking estratégico en LinkedIn' el 5 de abril. Plazas limitadas a 15 participantes. ¡Inscríbete ya!",
    time: "Hace 1 día",
    likes: 22,
    comments: 4,
  },
];

// ─── Testimonials (for landing page) ────────────────────────────────
export const MOCK_TESTIMONIALS = [
  {
    name: "Amina Diallo",
    region: "Senegal",
    university: "Universidad de Barcelona",
    quote: "Gracias a Puente conseguí mis primeras prácticas en Deloitte. Mi mentora me ayudó a adaptar mi CV y prepararme para las entrevistas.",
    avatar: "AD",
    color: "bg-pink-400",
    outcome: "Prácticas en Deloitte",
  },
  {
    name: "Wei Zhang",
    region: "China",
    university: "IE University",
    quote: "El taller de regulaciones migratorias fue clave para entender mis opciones legales. Ahora tengo mi permiso de trabajo y un empleo en tech.",
    avatar: "WZ",
    color: "bg-yellow-400",
    outcome: "Empleo en Glovo",
  },
  {
    name: "Carlos Mendoza",
    region: "Colombia",
    university: "Universidad Complutense",
    quote: "Lo mejor de Puente es la comunidad. Conocí a otros estudiantes internacionales que se convirtieron en mi red de apoyo en España.",
    avatar: "CM",
    color: "bg-blue-400",
    outcome: "Red de 50+ contactos",
  },
];

// ─── Program Stats (for landing page) ───────────────────────────────
export const MOCK_PROGRAM_STATS = {
  studentsActive: 127,
  mentorsActive: 24,
  companiesPartner: 18,
  workshopsCompleted: 42,
  placementRate: 78,
  averageNPS: 92,
  countriesRepresented: 23,
  sessionsDelivered: 384,
};

// ─── Upcoming Sessions (for profile page) ───────────────────────────
export const MOCK_UPCOMING_SESSIONS = [
  {
    type: "Mentoría 1:1",
    mentor: "Elena García Ruiz",
    date: "20 Mar 2026",
    time: "16:00 - 17:00",
    format: "Online (Google Meet)",
    topic: "Revisión de CV y estrategia de búsqueda",
    status: "confirmed",
  },
  {
    type: "Taller Grupal",
    mentor: "Isabel Fernández",
    date: "29 Mar 2026",
    time: "16:00 - 18:00",
    format: "Presencial - Madrid",
    topic: "Regulaciones migratorias para estudiantes",
    status: "registered",
  },
  {
    type: "Speed Networking",
    mentor: null,
    date: "8 Abr 2026",
    time: "18:00 - 20:00",
    format: "Presencial - Madrid",
    topic: "Evento con empresas colaboradoras",
    status: "open",
  },
];

// ─── Notifications ──────────────────────────────────────────────────
export const MOCK_NOTIFICATIONS = [
  {
    type: "session",
    message: "Tienes una sesión de mentoría en 2 días con Elena García Ruiz",
    time: "Hace 1h",
    read: false,
  },
  {
    type: "workshop",
    message: "Nuevo taller disponible: 'Networking estratégico en LinkedIn'",
    time: "Hace 3h",
    read: false,
  },
  {
    type: "job",
    message: "Nueva oportunidad: Desarrollador/a Junior Frontend en Cabify",
    time: "Hace 1 día",
    read: true,
  },
  {
    type: "community",
    message: "Carlos Mendoza te mencionó en un comentario",
    time: "Hace 1 día",
    read: true,
  },
  {
    type: "profile",
    message: "Completa tu perfil al 70% para aparecer en el matching con empresas",
    time: "Hace 2 días",
    read: true,
  },
];

// ─── Conversations (for messaging) ──────────────────────────────────
export const MOCK_CONVERSATIONS = [
  {
    id: "conv-1",
    participant: { name: "Elena García Ruiz", avatar: "EG", color: "bg-indigo-400" },
    messages: [
      { from: "Elena García Ruiz", text: "Hola Priya, quería confirmar nuestra sesión del jueves a las 16:00. ¿Tienes tu CV actualizado?", time: "14:30" },
      { from: "Priya Sharma", text: "¡Hola Elena! Sí, lo actualicé con el formato europeo que vimos. Te lo envío antes de la sesión.", time: "14:45" },
      { from: "Elena García Ruiz", text: "Perfecto. También quiero que preparemos una lista de 5 empresas objetivo para tu búsqueda.", time: "14:48" },
      { from: "Priya Sharma", text: "Genial. Ya tengo algunas en mente: Cabify, Glovo y alguna consultora tech.", time: "15:02" },
      { from: "Elena García Ruiz", text: "Muy bien. El jueves las revisamos y definimos la estrategia de contacto para cada una. ¡Nos vemos!", time: "15:10" },
    ],
  },
  {
    id: "conv-2",
    participant: { name: "Equipo Puente", avatar: "P", color: "bg-emerald-500" },
    messages: [
      { from: "Equipo Puente", text: "¡Bienvenida a Puente, Priya! 🎉 Tu perfil ha sido creado exitosamente.", time: "10:00" },
      { from: "Equipo Puente", text: "Para acceder a todas las funcionalidades del programa, completa tu perfil al 70%. Esto incluye subir tu CV y añadir tu LinkedIn.", time: "10:01" },
      { from: "Equipo Puente", text: "Te hemos asignado a Elena García Ruiz como mentora. Ella se pondrá en contacto contigo pronto.", time: "10:02" },
      { from: "Priya Sharma", text: "¡Gracias! Estoy muy emocionada de empezar el programa.", time: "11:30" },
    ],
  },
  {
    id: "conv-3",
    participant: { name: "Carlos Mendoza", avatar: "CM", color: "bg-blue-400" },
    messages: [
      { from: "Carlos Mendoza", text: "¡Hola! Estamos formando un grupo de estudio para preparar entrevistas. ¿Te apuntas?", time: "09:00" },
      { from: "Priya Sharma", text: "¡Claro! Me vendría genial practicar. ¿Cuántos sois?", time: "09:15" },
      { from: "Carlos Mendoza", text: "Somos 4 por ahora: Amina, Wei, yo y tú si te unes. Nos reunimos los miércoles por la tarde.", time: "09:20" },
      { from: "Priya Sharma", text: "Perfecto, los miércoles me van bien. ¿Por dónde os reunís?", time: "09:25" },
      { from: "Carlos Mendoza", text: "Hacemos videollamada por Google Meet. Te paso el enlace el martes. 💪", time: "09:30" },
    ],
  },
  {
    id: "conv-4",
    participant: { name: "Isabel Fernández", avatar: "IF", color: "bg-rose-400" },
    messages: [
      { from: "Isabel Fernández", text: "Hola Priya, te escribo sobre la documentación para la renovación del NIE que mencionaste en el taller.", time: "11:00" },
      { from: "Isabel Fernández", text: "Necesitarás: pasaporte vigente, matrícula universitaria, seguro médico, justificante económico y el formulario EX-00.", time: "11:02" },
      { from: "Priya Sharma", text: "Muchas gracias Isabel. ¿Sabes cuánto tarda el proceso actualmente?", time: "12:00" },
      { from: "Isabel Fernández", text: "En Madrid está tardando entre 2-3 meses. Te recomiendo pedir cita cuanto antes en la oficina de extranjería.", time: "12:15" },
      { from: "Priya Sharma", text: "Entendido. Voy a reunir los documentos esta semana. ¡Gracias por la ayuda!", time: "12:20" },
      { from: "Isabel Fernández", text: "De nada. Si tienes cualquier duda con los documentos, no dudes en escribirme.", time: "12:25" },
    ],
  },
];

// ─── Mentor Availability (for booking) ──────────────────────────────
export const MOCK_MENTOR_AVAILABILITY = [
  { date: "20 Mar 2026", slots: ["10:00", "11:00", "16:00", "17:00"] },
  { date: "22 Mar 2026", slots: ["09:00", "10:00", "14:00", "15:00"] },
  { date: "25 Mar 2026", slots: ["11:00", "16:00", "17:00"] },
  { date: "27 Mar 2026", slots: ["10:00", "11:00", "14:00", "15:00", "16:00"] },
  { date: "29 Mar 2026", slots: ["09:00", "10:00"] },
  { date: "1 Abr 2026", slots: ["11:00", "14:00", "16:00", "17:00"] },
  { date: "3 Abr 2026", slots: ["09:00", "10:00", "11:00", "15:00"] },
  { date: "5 Abr 2026", slots: ["10:00", "14:00", "15:00", "16:00"] },
];

// ─── CV Data (for builder) ──────────────────────────────────────────
export const MOCK_CV_DATA = {
  personalInfo: {
    name: "Priya Sharma",
    email: "priya.sharma@upm.es",
    phone: "+34 612 345 678",
    location: "Madrid, España",
    linkedin: "",
    portfolio: "",
  },
  education: [
    {
      degree: "Grado en Ingeniería Informática",
      institution: "Universidad Politécnica de Madrid",
      period: "2023 - Presente",
      description: "Especialización en desarrollo de software y sistemas distribuidos.",
    },
    {
      degree: "Higher Secondary Certificate",
      institution: "Delhi Public School, Nueva Delhi",
      period: "2019 - 2021",
      description: "Ciencias con especialización en Matemáticas e Informática.",
    },
  ],
  experience: [
    {
      title: "Desarrolladora Web (Prácticas)",
      company: "TechStartup Madrid",
      period: "Jun 2025 - Sep 2025",
      description: "Desarrollo de interfaces con React. Implementación de APIs REST. Colaboración en equipo ágil.",
    },
  ],
  skills: ["React", "TypeScript", "Python", "SQL", "Git", "HTML/CSS", "Node.js", "Figma"],
  languages: [
    { name: "Hindi", level: "Nativo" },
    { name: "Inglés", level: "C1 - Avanzado" },
    { name: "Español", level: "B2 - Intermedio alto" },
  ],
};

// ─── Admin Stats (for coordinator dashboard) ────────────────────────
export const MOCK_ADMIN_STATS = {
  totalStudents: 127,
  activeStudents: 98,
  pendingApplications: 14,
  totalMentors: 24,
  activeSessions: 45,
  completedSessions: 384,
  workshopsThisMonth: 5,
  averageCompletion: 68,
  placementRate: 78,
  nps: 92,
  monthlyEnrollment: [
    { month: "Oct", students: 15 },
    { month: "Nov", students: 22 },
    { month: "Dic", students: 18 },
    { month: "Ene", students: 28 },
    { month: "Feb", students: 24 },
    { month: "Mar", students: 20 },
  ],
  regionDistribution: [
    { region: "Asia", count: 38 },
    { region: "LATAM", count: 42 },
    { region: "África", count: 28 },
    { region: "Oriente Medio", count: 12 },
    { region: "Europa (no UE)", count: 7 },
  ],
};

// ─── Job Requirements (for detail pages) ────────────────────────────
export const MOCK_JOB_REQUIREMENTS: Record<string, { requirements: string[]; benefits: string[] }> = {
  "becario-marketing": {
    requirements: ["Estudiante de Marketing, Comunicación o similar", "Nivel B2 de español", "Conocimientos de redes sociales", "Capacidad analítica y creativa", "Disponibilidad 20h/semana"],
    benefits: ["Remuneración de 800€/mes", "Horario flexible", "Formación continua", "Posibilidad de incorporación"],
  },
  "asistente-investigacion": {
    requirements: ["Estudiante de Ciencias Sociales o similar", "Experiencia en investigación cualitativa", "Nivel C1 de español", "Manejo de SPSS o R"],
    benefits: ["Contrato a media jornada", "Acceso a recursos universitarios", "Publicación de papers", "Mentoring académico"],
  },
  "dev-junior-frontend": {
    requirements: ["Conocimientos de React y TypeScript", "Familiaridad con Git", "Capacidad de trabajo en equipo", "Inglés profesional", "No se requiere experiencia previa"],
    benefits: ["Salario competitivo: 28.000€/año", "100% remoto en España", "Equipo internacional", "Formación técnica continua", "Stock options"],
  },
  "ingeniero-procesos": {
    requirements: ["Estudiante de Ingeniería Química o Industrial", "Conocimientos de AutoCAD", "Nivel B2 de español", "Capacidad analítica"],
    benefits: ["900€/mes de remuneración", "Proyecto real en planta", "Mentor técnico asignado", "Posibilidad de TFG"],
  },
  "analista-datos": {
    requirements: ["Grado en Estadística, Matemáticas o similar", "Python y SQL avanzado", "Experiencia con herramientas de visualización", "Nivel B2 de español e inglés"],
    benefits: ["26.000€/año", "Modelo híbrido (2 días oficina)", "Plan de carrera", "Seguro médico privado"],
  },
  "community-manager": {
    requirements: ["Experiencia en gestión de redes sociales", "Conocimiento del mercado LATAM", "Español nativo o C2", "Creatividad y autonomía"],
    benefits: ["24.000€/año", "Oficina en Barcelona", "Ambiente startup", "Descuentos en Glovo", "Team buildings mensuales"],
  },
};

// ─── Workshop Agenda (for detail pages) ─────────────────────────────
export const MOCK_WORKSHOP_AGENDA: Record<string, string[]> = {
  "cv-europeo": ["Diferencias entre CV americano y europeo", "Estructura y secciones obligatorias", "Foto profesional: sí o no", "Adaptar experiencia internacional", "Ejercicio práctico: reescribe tu CV", "Feedback grupal"],
  "regulaciones-migratorias": ["Marco legal para estudiantes no-UE", "Permiso de estancia por estudios", "Modificación a permiso de trabajo", "NIE y empadronamiento", "Casos prácticos y preguntas", "Recursos y contactos útiles"],
  "networking-linkedin": ["Tu perfil de LinkedIn como landing page", "Estrategia de conexiones", "Cómo escribir mensajes de networking", "Participar en grupos y publicar", "LinkedIn para buscar empleo", "Plan de acción semanal"],
  "entrevistas-tecnicas": ["Tipos de entrevistas técnicas", "Preparación de algoritmos básicos", "System design para juniors", "Preguntas de behavioral interview", "Simulacro en parejas", "Feedback y mejora"],
  "elevator-pitch": ["¿Qué es un elevator pitch?", "Estructura: gancho, propuesta, cierre", "Tu historia en 60 segundos", "Práctica individual", "Presentación ante el grupo", "Tips para eventos de networking"],
};
